### ISSUE TITLE
Test if device is up uses TCP, OTA listens on UDP?

### ISSUE THREAD

**Issue by jnicolson** [arduino/board-discovery#3]
Was looking for why arduino-cli doesn't show network boards and tracked it back to this test:

https://github.com/arduino/board-discovery/blob/1ba29327fb0cd77c44823490c43433475f5379c6/network.go#L80

I could be mistaken, but it looks like ArduinoOTA for both ESP8266 and ESP32 use UDP but this tries to connect to TCP, fails, then the SSH port and also fails.

Unfortunately the easy fix of swapping it to udp didn't work and i'm unsure why, but i'll keep investigating.

**Comment by jnicolson** [comment]
On further investigation, i'm not sure this could have ever worked - string() returns the character for an ASCII code, not a string version of an int (that would be strconv.Itoa().

If this is the only fix it's easy, but i'm not sure if other implementations of Arduino OTA use TCP instead of UDP and therefore a check is needed.

**Comment by facchinm** [comment]
Hi @jnicolson ,
this package is only used by `arduino-cli` at the moment and is being phased out in favour of https://github.com/arduino/mdns-discovery . 
However, feel free to post a PR to fix any incorrect behaviour you may find!

**Comment by jnicolson** [comment]
Hi @facchinm,
Thanks for the reply and information.  I'll submit a PR shortly anyway with the knowledge that it'll only be temporary until the new discovery component is ready.
That said, investigating further it turns out arduino-cli doesn't seem to support the network upload protocol, but thats something to fix in that repo :)
